language: scala
scala:
  - 2.11.7

jdk:
  - oraclejdk8

install:
  - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.bz2
  - tar -xzvf protobuf-2.6.1.tar.bz2
  - cd protobuf-2.6.1 && ./configure --prefix=/usr && make && sudo make install && cd .. && rm -rf protobuf-2.6.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
